use serde::{Deserialize, Serialize};
use std::path::Path;

/// Registry manifest for a competition.
/// Each competition has a versioned manifest file that defines metadata,
/// scheduling rules, and references to team/player data files.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompetitionManifest {
    /// Schema version for forward compatibility.
    pub version: u32,
    /// Competition metadata.
    pub competition: ManifestCompetition,
    /// Competition rules.
    pub rules: ManifestRules,
    /// Phase definitions.
    pub phases: Vec<ManifestPhase>,
    /// Path to the directory containing teams/players data files.
    /// Relative to the manifest file location.
    pub data_path: String,
    /// Reference to the teams + players seed file (relative to data_path).
    pub seed_file: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManifestCompetition {
    pub id: String,
    pub name: String,
    pub slug: String,
    pub region: String,
    pub tier: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManifestRules {
    pub points_for_win: u8,
    pub points_for_draw: u8,
    pub best_of_default: u8,
    pub has_playoffs: bool,
    pub playoff_best_of: u8,
    pub teams_count: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManifestPhase {
    pub id: String,
    pub name: String,
    pub phase_type: String,
    pub scheduling: ManifestScheduling,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManifestScheduling {
    /// For RoundRobin: number of rounds (matches per team).
    pub rounds: Option<u32>,
    /// Whether each pair plays twice (home/away).
    pub double_round_robin: Option<bool>,
    /// For SingleElimination: best-of for each match.
    pub best_of: Option<u8>,
    /// Number of teams that qualify for this phase.
    pub teams_count: Option<usize>,
    /// Days of the week fixtures are played (0=Monday, 6=Sunday).
    pub days: Option<Vec<u8>>,
    /// Number of matches per matchday.
    pub matches_per_day: Option<u8>,
    /// Days from season start to first matchday.
    pub start_offset_days: Option<u32>,
}

/// Seed team as loaded from the seed file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SeedTeam {
    pub id: String,
    pub slug: String,
    pub name: String,
    pub code: String,
    pub home_league: Option<String>,
    pub region: Option<String>,
    pub players: Vec<SeedPlayer>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SeedPlayer {
    pub id: String,
    pub summoner_name: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub role: String,
    pub date_of_birth: Option<String>,
    pub nationality: Option<String>,
}

/// The full structure of a seed file (as generated by the scraper).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SeedData {
    pub source: Option<String>,
    pub league: Option<String>,
    pub teams: Vec<SeedTeam>,
}

/// Result of loading a competition manifest.
#[derive(Debug)]
pub struct LoadedManifest {
    pub manifest: CompetitionManifest,
    pub seed_data: Option<SeedData>,
}

/// Errors that can occur during manifest loading.
#[derive(Debug)]
pub enum LoadError {
    NotFound(String),
    InvalidJson(String),
    MissingField(String),
    VersionUnsupported(u32),
    SeedNotFound(String),
    InsufficientData(String),
}

// ---------------------------------------------------------------------------
// Loader
// ---------------------------------------------------------------------------

/// Load a competition manifest from a JSON file path.
pub fn load_manifest<P: AsRef<Path>>(manifest_path: P) -> Result<LoadedManifest, LoadError> {
    let path = manifest_path.as_ref();
    let json = std::fs::read_to_string(path)
        .map_err(|e| LoadError::NotFound(format!("manifest not found at {}: {e}", path.display())))?;

    let manifest: CompetitionManifest = serde_json::from_str(&json)
        .map_err(|e| LoadError::InvalidJson(format!("invalid manifest JSON: {e}")))?;

    // Validate version
    if manifest.version != 1 {
        return Err(LoadError::VersionUnsupported(manifest.version));
    }

    // Validate Tier 1 requirements
    validate_tier1(&manifest)?;

    // Load seed data
    let manifest_dir = path.parent().unwrap_or_else(|| Path::new("."));
    let data_dir = manifest_dir.join(&manifest.data_path);
    let seed_path = data_dir.join(&manifest.seed_file);

    let seed_data = if seed_path.exists() {
        let seed_json = std::fs::read_to_string(&seed_path)
            .map_err(|e| LoadError::SeedNotFound(format!("seed file at {}: {e}", seed_path.display())))?;
        serde_json::from_str(&seed_json)
            .map_err(|e| LoadError::InvalidJson(format!("invalid seed JSON: {e}")))
            .map(Some)?
    } else {
        None
    };

    Ok(LoadedManifest { manifest, seed_data })
}

/// Validate Tier 1 competition requirements.
fn validate_tier1(manifest: &CompetitionManifest) -> Result<(), LoadError> {
    if manifest.competition.tier != "Regional" {
        return Ok(()); // Only validate Tier 1 (Regional)
    }

    if manifest.rules.teams_count == 0 {
        return Err(LoadError::InsufficientData("teams_count must be > 0".into()));
    }

    if manifest.seed_file.is_empty() {
        return Err(LoadError::InsufficientData(
            "Tier 1 competition must specify a seed_file".into(),
        ));
    }

    // Must have at least one phase
    if manifest.phases.is_empty() {
        return Err(LoadError::InsufficientData(
            "Tier 1 competition must have at least one phase".into(),
        ));
    }

    // Each phase must have scheduling rules
    for phase in &manifest.phases {
        let sched = &phase.scheduling;
        match phase.phase_type.as_str() {
            "RoundRobin" => {
                if sched.rounds.is_none() {
                    return Err(LoadError::InsufficientData(
                        format!("phase '{}': RoundRobin requires scheduling.rounds", phase.id),
                    ));
                }
            }
            "SingleElimination" => {
                if sched.best_of.is_none() {
                    return Err(LoadError::InsufficientData(
                        format!("phase '{}': SingleElimination requires scheduling.best_of", phase.id),
                    ));
                }
            }
            _ => {}
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use std::path::PathBuf;

    fn make_manifest_json() -> String {
        r#"{
            "version": 1,
            "competition": {
                "id": "test-league",
                "name": "Test League",
                "slug": "test-league",
                "region": "TEST",
                "tier": "Regional"
            },
            "rules": {
                "points_for_win": 3,
                "points_for_draw": 1,
                "best_of_default": 1,
                "has_playoffs": true,
                "playoff_best_of": 5,
                "teams_count": 10
            },
            "phases": [
                {
                    "id": "regular",
                    "name": "Regular Season",
                    "phase_type": "RoundRobin",
                    "scheduling": {
                        "rounds": 18,
                        "double_round_robin": true,
                        "days": [6, 0],
                        "matches_per_day": 5,
                        "start_offset_days": 7
                    }
                }
            ],
            "data_path": ".",
            "seed_file": "teams.json"
        }"#
        .to_string()
    }

    #[test]
    fn valid_manifest_passes_validation() {
        let dir = tempfile::tempdir().unwrap();
        let manifest_path = dir.path().join("manifest.json");
        let mut f = std::fs::File::create(&manifest_path).unwrap();
        f.write_all(make_manifest_json().as_bytes()).unwrap();

        // Create seed file (empty — just needs to exist for path validation)
        // Actually the loader won't fail if seed doesn't exist for version=1
        // It just returns seed_data = None
        let result = load_manifest(&manifest_path);
        assert!(result.is_ok(), "manifest should load: {:?}", result.err());
    }

    #[test]
    fn manifest_missing_rounds_fails_validation() {
        let json = r#"{
            "version": 1,
            "competition": { "id": "x", "name": "X", "slug": "x", "region": "X", "tier": "Regional" },
            "rules": { "points_for_win": 3, "points_for_draw": 1, "best_of_default": 1, "has_playoffs": false, "playoff_best_of": 5, "teams_count": 10 },
            "phases": [{
                "id": "regular",
                "name": "Regular Season",
                "phase_type": "RoundRobin",
                "scheduling": { "double_round_robin": true }
            }],
            "data_path": ".",
            "seed_file": "teams.json"
        }"#;

        let dir = tempfile::tempdir().unwrap();
        let manifest_path = dir.path().join("manifest.json");
        let mut f = std::fs::File::create(&manifest_path).unwrap();
        f.write_all(json.as_bytes()).unwrap();

        let result = load_manifest(&manifest_path);
        assert!(result.is_err());
        match result.unwrap_err() {
            LoadError::InsufficientData(msg) => assert!(msg.contains("rounds")),
            other => panic!("expected InsufficientData, got {:?}", other),
        }
    }

    #[test]
    fn loads_lec_manifest_successfully() {
        let manifest_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent().unwrap()
            .parent().unwrap()
            .parent().unwrap()
            .join("data/competitions/lec/manifest.json");
        let result = load_manifest(&manifest_path);
        assert!(result.is_ok(), "LEC manifest should load: {:?}", result.err());

        let loaded = result.unwrap();
        assert_eq!(loaded.manifest.competition.id, "lec");
        assert_eq!(loaded.manifest.rules.teams_count, 10);
        assert!(loaded.seed_data.is_some(), "LEC seed data should exist");
    }

    #[test]
    fn loads_cblol_manifest_successfully() {
        let manifest_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent().unwrap()
            .parent().unwrap()
            .parent().unwrap()
            .join("data/competitions/cblol/manifest.json");
        let result = load_manifest(&manifest_path);
        assert!(result.is_ok(), "CBLOL manifest should load: {:?}", result.err());

        let loaded = result.unwrap();
        assert_eq!(loaded.manifest.competition.id, "cblol");
        assert_eq!(loaded.manifest.competition.region, "BRAZIL");
        assert_eq!(loaded.manifest.rules.teams_count, 10);

        // CBLOL has inline seed_data
        assert!(loaded.seed_data.is_some(), "CBLOL seed data should exist");
        if let Some(seed) = &loaded.seed_data {
            assert_eq!(seed.teams.len(), 10, "CBLOL should have 10 teams");
        }
    }

    #[test]
    fn unsupported_version_fails() {
        let json = r#"{
            "version": 99,
            "competition": { "id": "x", "name": "X", "slug": "x", "region": "X", "tier": "Regional" },
            "rules": { "points_for_win": 3, "points_for_draw": 1, "best_of_default": 1, "has_playoffs": false, "playoff_best_of": 5, "teams_count": 10 },
            "phases": [],
            "data_path": ".",
            "seed_file": ""
        }"#;

        let dir = tempfile::tempdir().unwrap();
        let manifest_path = dir.path().join("manifest.json");
        let mut f = std::fs::File::create(&manifest_path).unwrap();
        f.write_all(json.as_bytes()).unwrap();

        let result = load_manifest(&manifest_path);
        assert!(result.is_err());
        match result.unwrap_err() {
            LoadError::VersionUnsupported(v) => assert_eq!(v, 99),
            other => panic!("expected VersionUnsupported, got {:?}", other),
        }
    }
}
