import { readdirSync, writeFileSync } from "fs";
import { resolve } from "path";

const SKINS_DIR = resolve("public/champion-skins");
const OUT_FILE = resolve("src/assets/champion-skin-map.ts");

const map: Record<string, string[]> = {};

const entries = readdirSync(SKINS_DIR, { withFileTypes: true });
for (const entry of entries) {
  if (!entry.isDirectory()) continue;
  const championDir = resolve(SKINS_DIR, entry.name);
  const files = readdirSync(championDir)
    .filter((f) => f.endsWith(".webp"))
    .map((f) => `/champion-skins/${entry.name}/${f}`);
  if (files.length > 0) {
    map[entry.name] = files;
  }
}

const content = `// Generated by scripts/generate-skin-manifest.ts — do not edit manually
export const CHAMPION_SKIN_MAP: Record<string, string[]> = ${JSON.stringify(map)};\n`;

writeFileSync(OUT_FILE, content);
console.log(`Generated champion skin map: ${Object.keys(map).length} champions, ${Object.values(map).flat().length} files → ${OUT_FILE}`);
